# Generated by Django 5.0.6 on 2024-07-01 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.IntegerField()),
                ('delivery_place', models.CharField(max_length=255)),
                ('delivery_term', models.CharField(max_length=255)),
                ('specification', models.FileField(upload_to='uploads/request')),
                ('boq', models.FileField(upload_to='uploads/request/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rfq_ref', models.IntegerField()),
                ('deadline_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_type', models.CharField(max_length=100)),
                ('line_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_date', models.DateField()),
                ('payment', models.CharField(max_length=100)),
                ('lead_time', models.IntegerField()),
                ('file', models.FileField(upload_to='uploads/bids/')),
                ('boq_total', models.FileField(upload_to='uploads/bids/')),
                ('bid_status', models.CharField(default=0, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quotation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationline')),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationrequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
