# Generated by Django 5.0.6 on 2024-07-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
