# Generated by Django 5.0.6 on 2024-07-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='unit_price',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
