# Generated by Django 5.0.6 on 2024-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_remove_quotationline_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='boq',
            field=models.FileField(null=True, upload_to='uploads/request/'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='delivery_term',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='specification',
            field=models.FileField(null=True, upload_to='uploads/request'),
        ),
    ]
