# Generated by Django 5.0.6 on 2024-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_supplierbid_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbid',
            name='vat',
            field=models.IntegerField(),
        ),
    ]
