# Generated by Django 5.0.6 on 2024-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_alter_supplierbid_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbid',
            name='delivery_term',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
