# Generated by Django 5.0.6 on 2024-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_supplierbid_delivery_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbid',
            name='delivery_term',
            field=models.CharField(default='', max_length=100),
        ),
    ]
